Update Gatus.yml

diff --git a/.github/workflows/Setup_Gatus.yml b/.github/workflows/Setup_Gatus.yml
--- a/.github/workflows/Setup_Gatus.yml
+++ b/.github/workflows/Setup_Gatus.yml
@@ -1,25 +1,41 @@
-name: Setup Gatus
+name: Setup Gatus on the VM with Ansible
 
 on:
-  push:
-    paths:
-      - playbooks/docker.yml
-      - roles/docker_setup/**
-
-  workflow_dispatch:
-    inputs:
-      environment:
-        description: "Select the environment (dev, stage, prod)"
-        required: true
-        default: "dev"
-
+    workflow_dispatch:
+        inputs:
+            environment:
+                type: choice
+                description: Butaforinis pasirinkimas 2
+                options:
+                    - dev
+                default: dev
 jobs:
-  setup-gatus:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
 
-      - name: Run Ansible Playbook
-        run: |
-          ansible-playbook -i inventory/${{ github.event.inputs.environment }} playbooks/docker.yml
+    install-docker:
+        runs-on: ubuntu-latest
+        defaults:
+            run:
+              working-directory: ./ansible
+        steps:
+        #Checkout code so that the palybook is accessible
+            - name: Checkout code
+              uses: actions/checkout@v3
+
+            - name: Check and Install Ansible
+              run: |
+                if ! command -v ansible &> /dev/null; then
+                  echo "Ansible not found. Installing..."
+                  sudo apt-get update && sudo apt-get install -y ansible
+                else
+                  echo "Ansible is already installed."
+                fi
+
+
+            - name: Setup SSH key for connection to AWS VM
+              run: |
+                mkdir -p ~/.ssh
+                echo "${{secrets.AWS_SSH_KEY}}" > ~/.ssh/id_rsa
+                chmod 600 ~/.ssh/id_rsa
+
+            - name: Run Gatus playbook to install Gatus
+              run: ansible-playbook -u ubuntu -i 3.126.101.111, --private-key ~/.ssh/id_rsa gatus.yml
